version: '3'
services:
  app1:
    container_name: app1
    build: .
    environment:
      - FEATUREHUB_API_KEY=default/4ad25e95-35fc-4e2e-a367-9fbccb5108e6/wfw3wKcKSrAtedNflYE1w6rMRQX9nfvrrVEzbZHY
      - FEATUREHUB_CLIENT_API_KEY=default/89e3287d-3daa-4e9e-9574-15f44d0ee89f/6MneViwRIJaGBeyF86OcyAynO4M1Fw*dSINPIfR64ZZEeqbWVHa
      - FEATUREHUB_EDGE_URL=http://192.168.0.25:8553
      - SERVICE_PORT=8888
      - NOTIFICATION_SERVICE_URL=https://webhook.site/46852086-b65f-4b03-9e7e-ad8070ff5108
    ports:
      - 8888:8888
  app2:
    container_name: app2
    build: .
    environment:
      - FEATUREHUB_API_KEY=default/4ad25e95-35fc-4e2e-a367-9fbccb5108e6/wfw3wKcKSrAtedNflYE1w6rMRQX9nfvrrVEzbZHY
      - FEATUREHUB_CLIENT_API_KEY=default/89e3287d-3daa-4e9e-9574-15f44d0ee89f/6MneViwRIJaGBeyF86OcyAynO4M1Fw*dSINPIfR64ZZEeqbWVHa
      - FEATUREHUB_EDGE_URL=http://192.168.0.25:8553
      - SERVICE_PORT=8889
      - NOTIFICATION_SERVICE_URL=https://webhook.site/46852086-b65f-4b03-9e7e-ad8070ff5108
    ports:
      - 8889:8889